
import lmcache

import sys

from lmcache_ascend import c_ops
sys.modules['lmcache.c_ops'] = c_ops

from lmcache_ascend.mindspore.v1.memory_management import _allocate_cpu_memory
lmcache.v1.memory_management._allocate_cpu_memory = _allocate_cpu_memory

from lmcache_ascend.mindspore.v1.memory_management import NumpyAndTensorMemoryObj
lmcache.v1.memory_management.TensorMemoryObj = NumpyAndTensorMemoryObj

from lmcache_ascend.mindspore.v1.memory_management import NumpyAndTensorMemoryAllocator
lmcache.v1.memory_management.TensorMemoryAllocator = NumpyAndTensorMemoryAllocator

import lmcache.v1.storage_backend
from lmcache_ascend.mindspore.v1.storage_backend.abstract_backend import StorageBackendInterface___init__
lmcache.v1.storage_backend.StorageBackendInterface.__init__ = StorageBackendInterface___init__

import lmcache.v1.storage_backend.connector.mooncakestore_connector as mooncakestore_connector
from lmcache_ascend.mindspore.v1.storage_backend.connector.mooncakestore_connector import MooncakeStoreConnector__register_cpu_buffer
mooncakestore_connector.MooncakestoreConnector._register_cpu_buffer = MooncakeStoreConnector__register_cpu_buffer

from lmcache_ascend.mindspore.v1.storage_backend.connector.mooncakestore_connector import MooncakeStoreConnector__batch_get_into
mooncakestore_connector.MooncakestoreConnector._batch_get_into = MooncakeStoreConnector__batch_get_into

from lmcache_ascend.mindspore.v1.storage_backend.connector.mooncakestore_connector import MooncakeStoreConnector__put_without_metadata
mooncakestore_connector.MooncakestoreConnector._put_without_metadata = MooncakeStoreConnector__put_without_metadata

from lmcache_ascend.mindspore.v1.npu_connector import VLLMPagedMemNPUConnectorV2
import lmcache.v1.gpu_connector
lmcache.v1.gpu_connector.VLLMPagedMemGPUConnectorV2 = VLLMPagedMemNPUConnectorV2

import lmcache.v1.system_detection
from lmcache_ascend.mindspore.v1.system_detection import _read_from_sys
lmcache.v1.system_detection.NUMADetector._read_from_sys = _read_from_sys